name: build and distribute

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'static/**'
  release:
    types: [published]
jobs:
  build-n-publish:
    name: Build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive 
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '8'
        architecture: x64
    - name: Build microrts
      run: bash build.sh
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Build a source tarball
      run: uv build --sdist
    - name: Upload artifact to S3
      uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: microrts
        source_dir: dist
        destination_dir: /microrts/artifacts
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      run: uv publish --token ${{ secrets.pypi_password }}
